# Generated by Django 5.2.7 on 2025-12-01 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_unit_alter_transaction_transaction_type_unitpurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='unit_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UnitUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_used', models.PositiveIntegerField()),
                ('service_description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
