# Generated by Django 5.2.7 on 2025-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_of_birth_user_full_address_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bundle_sid',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
