# Generated by Django 5.2.7 on 2025-11-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_numbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
