# Generated by Django 5.2.7 on 2025-11-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_numbers', '0002_country'),
    ]

    operations = [
    ]
