# Generated by Django 5.2.7 on 2025-11-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_numbers', '0003_populate_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioNumberPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='twilionumber',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
