# Generated by Django 5.2.7 on 2025-11-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_numbers', '0004_twilionumberprice_twilionumber_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilionumber',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilionumber',
            name='subscription_status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
