# Generated by Django 5.2.7 on 2025-11-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_numbers', '0005_twilionumber_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('outbound_call', 'Outbound Call (per minute)'), ('inbound_call', 'Inbound Call (per minute)'), ('sms', 'SMS (per message)')], max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Cost per unit of service', max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
