# Generated by Django 5.2.7 on 2025-11-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_numbers', '0006_servicerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='service_type',
            field=models.CharField(choices=[('outbound_call', 'Outbound Call (per minute)'), ('inbound_call', 'Inbound Call (per minute)'), ('outbound_sms', 'Outbound SMS (per message)'), ('inbound_sms', 'Inbound SMS (per message)')], max_length=20, unique=True),
        ),
    ]
