# Generated by Django 5.2.7 on 2025-12-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_purchase_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('call_unit_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('message_unit_rate', models.DecimalField(decimal_places=2, default=0.5, max_digits=10)),
            ],
        ),
    ]
